### PR TITLE
Added applyKey to order

### PR DESCRIPTION
**Pull request by marquesarthur**
Pull request addresses: 
* https://piazza.com/class/jalkvszhpv4r6?cid=463
* https://piazza.com/class/jalkvszhpv4r6?cid=494

### CODE REVIEW

**Comment by rtholmes** [comment]
It looks like this PR has merge conflicts?

**Comment by rtholmes** [comment]
@marquesarthur I don't want to cause a problem by pulling in a merge conflict, if you get a chance could you figure out what needs to happen here?

**Comment by marquesarthur** [comment]
sure

**Comment by rtholmes** [comment]
@marquesarthur still seeing merge conflicts. Should we just delete this PR and do a clean one?
image

**Comment by marquesarthur** [comment]
@rtholmes please delete this pull request and consider the newly submitted one. I don't know what cause the merge conflict. :-(

**Pull request closed without merging**
